# Generated by Django 4.0.4 on 2022-06-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('instno', models.IntegerField()),
                ('instdate', models.DateField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallyapp.particulars')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallyapp.account')),
                ('transactiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallyapp.transactiontype')),
            ],
        ),
    ]
