# Generated by Django 4.0.4 on 2022-06-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0003_remove_receipt_instdate_remove_receipt_instno_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receiptbank',
            new_name='bankreceipt',
        ),
    ]
